#!/bin/bash
# DEPLOYMENT SCRIPT - Run these commands step by step

echo "═══════════════════════════════════════════════════════════════════════════"
echo "  Citizen Issue Reporting System - Deployment Script"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""

# STEP 1: Initialize Git
echo "STEP 1: Initialize Git Repository"
echo "───────────────────────────────────────────────────────────────────────────"
echo "Run these commands:"
echo ""
echo "  cd \"c:\VS\Reporting system\""
echo "  git init"
echo "  git add ."
echo "  git commit -m \"Initial commit - ready for production deployment\""
echo "  git remote add origin https://github.com/YOUR_USERNAME/reporting-system.git"
echo "  git push -u origin main"
echo ""
echo "⏳ Time: ~5 minutes"
echo ""
echo "Press Enter after pushing to GitHub..."
read

# STEP 2: Railway Backend
echo ""
echo "STEP 2: Deploy Backend to Railway"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Go to https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'Create New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose your 'reporting-system' repository"
echo "6. Click 'Deploy Now'"
echo ""
echo "WHILE DEPLOYING, Go to Settings → Variables and add:"
echo ""
echo "  GOOGLE_CLIENT_ID=<your_value>"
echo "  FIREBASE_PROJECT_ID=<your_value>"
echo "  FIREBASE_CLIENT_EMAIL=<your_value>"
echo "  FIREBASE_PRIVATE_KEY=<your_value>"
echo "  GMAIL_USER=<your_value>"
echo "  GMAIL_APP_PASSWORD=<your_value>"
echo ""
echo "7. After deployment succeeds, copy your Railway URL"
echo ""
echo "Your Railway URL should look like:"
echo "  https://reporting-system-production.up.railway.app"
echo ""
echo "⏳ Time: ~5-10 minutes"
echo ""
echo "Press Enter after Railway deployment is complete..."
read

# STEP 3: Vercel Frontend
echo ""
echo "STEP 3: Deploy Frontend to Vercel"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. Go to https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Click 'Add New' → 'Project'"
echo "4. Select your 'reporting-system' repository"
echo "5. Click 'Deploy'"
echo ""
echo "No environment variables needed for Vercel!"
echo ""
echo "After deployment, your Vercel URL should look like:"
echo "  https://reporting-system.vercel.app"
echo ""
echo "⏳ Time: ~3-5 minutes"
echo ""
echo "Press Enter after Vercel deployment is complete..."
read

# STEP 4: Verification
echo ""
echo "STEP 4: Verify Deployments"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "Test the following:"
echo ""
echo "1. Backend Health Check:"
echo "   Open: https://your-railway-url/health"
echo "   Should show: {\"status\":\"ok\"}"
echo ""
echo "2. Frontend:"
echo "   Open: https://your-vercel-url"
echo "   Should show: Google Sign-in button"
echo ""
echo "3. Test Full Flow:"
echo "   - Click 'Sign in with Google'"
echo "   - Click 'Select Location'"
echo "   - Click on map to select location"
echo "   - Verify city/pincode auto-fill"
echo "   - Test pincode search"
echo "   - Submit form"
echo "   - Verify email received"
echo "   - Check Firestore for database entry"
echo ""
echo "⏳ Time: ~10 minutes"
echo ""
echo "Press Enter after verification..."
read

# STEP 5: Optional - Update Google OAuth
echo ""
echo "STEP 5: (Optional) Update Google OAuth"
echo "───────────────────────────────────────────────────────────────────────────"
echo ""
echo "If Google Sign-In fails after deployment:"
echo ""
echo "1. Go to https://console.cloud.google.com"
echo "2. Select your project"
echo "3. Go to 'APIs & Services' → 'Credentials'"
echo "4. Click your OAuth 2.0 Client ID"
echo "5. Under 'Authorized redirect URIs', add:"
echo ""
echo "   https://your-vercel-url"
echo "   https://your-vercel-url/"
echo ""
echo "6. Click Save"
echo "7. Try signing in again"
echo ""
echo "⏳ Time: ~5 minutes"
echo ""

# Final Summary
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT COMPLETE!"
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "Your application is now live at:"
echo ""
echo "  📱 Frontend:  https://your-vercel-project.vercel.app"
echo "  🔧 Backend:   https://your-railway-project.up.railway.app"
echo ""
echo "Share your frontend URL with users!"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 For more help, see:"
echo "   - START_HERE.md"
echo "   - DEPLOY_NOW.md"
echo "   - DEPLOYMENT.md"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════"
